name=CYD
version=1.0.0
author=Evgeniy Shitov
maintainer=Evgeniy Shitov
sentence=Library for ESP32-2432S028 (Cheap Yellow Display) with LovyanGFX
paragraph=Display ILI9341 240x320, touch XPT2046, RGB LED, backlight control.
category=Display
url=https://github.com/shitov-evgeniy/CYD
architectures=esp32
depends=LovyanGFX
